baseURL = 'https://devfest23.gdgvenezia.it/'
languageCode = 'it-IT'
paginate = 6
theme= "coHub"
title = 'DevFest Venezia 23'

  # Main Menu
[[menu.Main]]
name = "Speakers"
url= "/speakers/"
weight = 1
#  [[menu.Main]]
#  name = "Agenda"
#  url= "/agenda/"
#  weight = 2
[[menu.Main]]
name = "Tickets"
url= "#ticket"
weight = 2
[[menu.Main]]
name = "Partners"
url= "#partner"
weight = 3
[[menu.Main]]
name = "Location"
url= "#location"
weight = 4
#  [[menu.Main]]

[params]
  description = "DevFest Venezia 2023 - 2 Dicembre - Venezia"
  copyright = "© {year} <a href=\"https://marcogomiero.com/\" target=\"_blank\">Marco Gomiero </a>"
  googleAnalytics = ""
  image = "images/logo.png"
  logo = "images/logo.svg"
  footerlogo = "images/logo.svg"
  footerDescription = "Organized by Google Developer Group <a href=\"https://gdg.community.dev/gdg-venezia/\" target=\"BLANK\">Venezia</a>."

  [params.location]
  title = "Location"

  [params.location.venezia]
  address = "Campus Scientifico Università Ca' Foscari"
  desc = "Via Torino, 155 Mestre, Venezia VE, 30170"
  mapsLink = "https://www.google.com/maps/dir//Via%20Torino%2C%20155%20Mestre%2C%20Venezia%20VE"

